id: A7DB35E07
title: Toh_122-Wisdom_at_the_Hour_of_Death-v1
type: translation
pechas:
- I068C0160
- I570DE544
source_metadata:
  creationtool: 84000-translation-memory
  creationtoolversion: 1.0.0.0
  datatype: PlainText
  segtype: phrase
  adminlang: en
  srclang: bo
  o-tmf: TEI
  creationdate: '2018-03-26T16:01:47.493Z'
  creationid: celso
  eft-text-id: UT22084-054-003
  xmlns-eft: http://read.84000.co/ns/1.0
  title: Toh_122-Wisdom_at_the_Hour_of_Death-v1
alignment_to_base:
  I068C0160/B55D: '6226'
  I570DE544/0A2A: '6226'
